version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    container_name: nodejs
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ../nodejs:/workspace/nodejs:cached
      - node_modules_volume:/workspace/nodejs/node_modules
    networks:
      - nodejs-network
    stdin_open: true
    tty: true

networks:
  nodejs-network:
    driver: bridge

volumes:
  node_modules_volume:
